language: java
jdk: oraclejdk9

install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V -P codacycoverage
script:
  - mvn clean jacoco:prepare-agent install jacoco:report  -P codacycoverage
after_success:
  - mvn coveralls:report -P no-docker,coveralls
